### ISSUE TITLE
falta holamundo.php

### ISSUE THREAD

**Issue by joelmatiassilva** [Komoshi/desdecero#1]
Necesitaría el archivo php para trabajar en forma local.

**Comment by Dianaman** [comment]
Aca te lo mando

**Comment by Dianaman** [comment]
Uh perdon, te mande otra cosa jaja

**Comment by joelmatiassilva** [comment]
hacete un commit negri. así no perdemos la construmbre

**Comment by Dianaman** [comment]
de desdecero? me dice que no hay nada nuevo

2015-08-28 12:50 GMT-03:00 joel matias notifications@github.com:

**Comment by joelmatiassilva** [comment]
está holamundo.php en el proyecto? Si no es así agregalo y lo puseas. Sino otro camino es crear otro repo y pones el codigo de servidor.

**Comment by Dianaman** [comment]
ahi lo agregue, no se si esta bien donde lo puse

**Comment by joelmatiassilva** [comment]
por le momento está bien.
